// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Design",
    "CA1062:Validate arguments of public methods",
    Justification = "Code generated by Entity Framework",
    Scope = "namespaceanddescendants",
    Target = "N:ShortURL.Data.Migrations")]
[assembly: SuppressMessage("Roslynator",
    "RCS1021:Convert lambda expression body to expression body",
    Justification = "Code generated by Entity Framework",
    Scope = "namespaceanddescendants",
    Target = "N:ShortURL.Data.Migrations")]
[assembly: SuppressMessage("Style",
    "IDE1006:Naming Styles",
    Justification = "Accept migration name starting with lower case",
    Scope = "namespaceanddescendants",
    Target = "N:ShortURL.Data.Migrations")]