name: dotnet outdated
run-name: ${{ github.actor }} is running dotnet outdated

on:
  pull_request:
  schedule:
    - cron: '0 5 * * 5'

jobs:
  dotnet-outdated:
    name: "dotnet outdated"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: mcld/dotnet-outdated-action@v4.1
